# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import streaming_pb2 as streaming__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamingServiceStub(object):
    """===== Serviço =====

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_unary(
                '/streaming.StreamingService/ListUsers',
                request_serializer=streaming__pb2.Empty.SerializeToString,
                response_deserializer=streaming__pb2.Users.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/streaming.StreamingService/GetUser',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.User.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/streaming.StreamingService/CreateUser',
                request_serializer=streaming__pb2.UserInput.SerializeToString,
                response_deserializer=streaming__pb2.User.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/streaming.StreamingService/UpdateUser',
                request_serializer=streaming__pb2.UserUpdate.SerializeToString,
                response_deserializer=streaming__pb2.User.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/streaming.StreamingService/DeleteUser',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.Empty.FromString,
                _registered_method=True)
        self.ListMusics = channel.unary_unary(
                '/streaming.StreamingService/ListMusics',
                request_serializer=streaming__pb2.Empty.SerializeToString,
                response_deserializer=streaming__pb2.Musics.FromString,
                _registered_method=True)
        self.GetMusic = channel.unary_unary(
                '/streaming.StreamingService/GetMusic',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.Music.FromString,
                _registered_method=True)
        self.CreateMusic = channel.unary_unary(
                '/streaming.StreamingService/CreateMusic',
                request_serializer=streaming__pb2.MusicInput.SerializeToString,
                response_deserializer=streaming__pb2.Music.FromString,
                _registered_method=True)
        self.UpdateMusic = channel.unary_unary(
                '/streaming.StreamingService/UpdateMusic',
                request_serializer=streaming__pb2.MusicUpdate.SerializeToString,
                response_deserializer=streaming__pb2.Music.FromString,
                _registered_method=True)
        self.DeleteMusic = channel.unary_unary(
                '/streaming.StreamingService/DeleteMusic',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.Empty.FromString,
                _registered_method=True)
        self.ListPlaylists = channel.unary_unary(
                '/streaming.StreamingService/ListPlaylists',
                request_serializer=streaming__pb2.Empty.SerializeToString,
                response_deserializer=streaming__pb2.Playlists.FromString,
                _registered_method=True)
        self.GetPlaylist = channel.unary_unary(
                '/streaming.StreamingService/GetPlaylist',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.Playlist.FromString,
                _registered_method=True)
        self.CreatePlaylist = channel.unary_unary(
                '/streaming.StreamingService/CreatePlaylist',
                request_serializer=streaming__pb2.PlaylistInput.SerializeToString,
                response_deserializer=streaming__pb2.Playlist.FromString,
                _registered_method=True)
        self.UpdatePlaylist = channel.unary_unary(
                '/streaming.StreamingService/UpdatePlaylist',
                request_serializer=streaming__pb2.PlaylistUpdate.SerializeToString,
                response_deserializer=streaming__pb2.Playlist.FromString,
                _registered_method=True)
        self.DeletePlaylist = channel.unary_unary(
                '/streaming.StreamingService/DeletePlaylist',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.Empty.FromString,
                _registered_method=True)
        self.PlaylistsByUser = channel.unary_unary(
                '/streaming.StreamingService/PlaylistsByUser',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.Playlists.FromString,
                _registered_method=True)
        self.MusicsByPlaylist = channel.unary_unary(
                '/streaming.StreamingService/MusicsByPlaylist',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.Musics.FromString,
                _registered_method=True)
        self.PlaylistsByMusic = channel.unary_unary(
                '/streaming.StreamingService/PlaylistsByMusic',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.Playlists.FromString,
                _registered_method=True)


class StreamingServiceServicer(object):
    """===== Serviço =====

    """

    def ListUsers(self, request, context):
        """---- Usuários (CRUD) ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMusics(self, request, context):
        """---- Músicas (CRUD) ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMusic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMusic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMusic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMusic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlaylists(self, request, context):
        """---- Playlists (CRUD) ----
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaylistsByUser(self, request, context):
        """---- Consultas relacionais (as 5 do enunciado) ----
        playlists de um usuário
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MusicsByPlaylist(self, request, context):
        """músicas de uma playlist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaylistsByMusic(self, request, context):
        """playlists que contêm a música
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=streaming__pb2.Empty.FromString,
                    response_serializer=streaming__pb2.Users.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.User.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=streaming__pb2.UserInput.FromString,
                    response_serializer=streaming__pb2.User.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=streaming__pb2.UserUpdate.FromString,
                    response_serializer=streaming__pb2.User.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.Empty.SerializeToString,
            ),
            'ListMusics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMusics,
                    request_deserializer=streaming__pb2.Empty.FromString,
                    response_serializer=streaming__pb2.Musics.SerializeToString,
            ),
            'GetMusic': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMusic,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.Music.SerializeToString,
            ),
            'CreateMusic': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMusic,
                    request_deserializer=streaming__pb2.MusicInput.FromString,
                    response_serializer=streaming__pb2.Music.SerializeToString,
            ),
            'UpdateMusic': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMusic,
                    request_deserializer=streaming__pb2.MusicUpdate.FromString,
                    response_serializer=streaming__pb2.Music.SerializeToString,
            ),
            'DeleteMusic': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMusic,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.Empty.SerializeToString,
            ),
            'ListPlaylists': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlaylists,
                    request_deserializer=streaming__pb2.Empty.FromString,
                    response_serializer=streaming__pb2.Playlists.SerializeToString,
            ),
            'GetPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylist,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.Playlist.SerializeToString,
            ),
            'CreatePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePlaylist,
                    request_deserializer=streaming__pb2.PlaylistInput.FromString,
                    response_serializer=streaming__pb2.Playlist.SerializeToString,
            ),
            'UpdatePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlaylist,
                    request_deserializer=streaming__pb2.PlaylistUpdate.FromString,
                    response_serializer=streaming__pb2.Playlist.SerializeToString,
            ),
            'DeletePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePlaylist,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.Empty.SerializeToString,
            ),
            'PlaylistsByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaylistsByUser,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.Playlists.SerializeToString,
            ),
            'MusicsByPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.MusicsByPlaylist,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.Musics.SerializeToString,
            ),
            'PlaylistsByMusic': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaylistsByMusic,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.Playlists.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.StreamingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streaming.StreamingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamingService(object):
    """===== Serviço =====

    """

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListUsers',
            streaming__pb2.Empty.SerializeToString,
            streaming__pb2.Users.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/GetUser',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/CreateUser',
            streaming__pb2.UserInput.SerializeToString,
            streaming__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/UpdateUser',
            streaming__pb2.UserUpdate.SerializeToString,
            streaming__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/DeleteUser',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMusics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListMusics',
            streaming__pb2.Empty.SerializeToString,
            streaming__pb2.Musics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMusic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/GetMusic',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.Music.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMusic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/CreateMusic',
            streaming__pb2.MusicInput.SerializeToString,
            streaming__pb2.Music.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMusic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/UpdateMusic',
            streaming__pb2.MusicUpdate.SerializeToString,
            streaming__pb2.Music.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMusic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/DeleteMusic',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlaylists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListPlaylists',
            streaming__pb2.Empty.SerializeToString,
            streaming__pb2.Playlists.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/GetPlaylist',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/CreatePlaylist',
            streaming__pb2.PlaylistInput.SerializeToString,
            streaming__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/UpdatePlaylist',
            streaming__pb2.PlaylistUpdate.SerializeToString,
            streaming__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/DeletePlaylist',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaylistsByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/PlaylistsByUser',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.Playlists.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MusicsByPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/MusicsByPlaylist',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.Musics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaylistsByMusic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/PlaylistsByMusic',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.Playlists.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
